In [11]:
import numpy as np
random_array = np.random.random((1000, 3))
print(random_array)




[[0.16018459 0.20324377 0.9435845 ]
 [0.92906558 0.41272486 0.95481485]
 [0.56519867 0.14813409 0.06458727]
 ...
 [0.91453116 0.47329843 0.25786558]
 [0.58351556 0.65783607 0.93317595]
 [0.5595971  0.71824001 0.73926157]]
